### ISSUE TITLE
Official integration

### ISSUE THREAD

**Issue by M5oul** [YunoHost-Apps/mumbleserver_ynh#10]
- [x] https://github.com/YunoHost-Apps/mumbleserver_ynh/pull/9 should validate levels 4 and 5.
- Level 6 is already validated.
- [x] [Certificates integration](https://github.com/YunoHost-Apps/mumbleserver_ynh/issues/8)
- [x] upgrade/backup/restore scripts.
- [x] [check port if port is already taken](https://ci-apps.yunohost.org/jenkins/job/mumbleserver%20(Community)/lastBuild/consoleFull).
- [x] use https://github.com/YunoHost/yunohost/pull/266 to avoid the [warning on deprecated tool](https://github.com/YunoHost-Apps/mumbleserver_ynh/blob/master/scripts/install#L18).

**Comment by Jibec** [comment]
As far as I know, this app fulfill these requirements. If @YunoHost-Apps/apps-group want to include it as official, I won't oppose.

**Comment by frju365** [comment]
Well, if you want your app to be integrated in the official one, pls open an issue on Yunohost/apps or wait for a community election.
