### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/mumbleserver_ynh#12]
Hello

I just tried to install Mumble, so I didn't just try, I did it :)
But, I encounter some issues.

- First, the manifest forced me to set a password for my server. Even if I don't want to set ones.
- Same thing for the welcome text. No default value.
- And, more annoying, I can't connect to my server by wifi. I always receive a "Could not open a connection to the host". But no problem by cable or 4G. And nothing in the log, of course.

**Comment by maniackcrudelis** [comment]
With an another app, Plumble for the first try, Mumble for the second, with android for both.
I received this error: "The host refused connection"
Still nothing in the log...

**Comment by M5oul** [comment]
>First, the manifest forced me to set a password for my server. Even if I don't want to set ones.
Same thing for the welcome text. No default value.

I also found this way of installing annoying.

**Comment by Jibec** [comment]
can you please confirm the wifi issue again @maniackcrudelis ?

**Comment by Jibec** [comment]
can't reproduce the issue as plumble always crash on my cellphone, please open this again if relevant
