### ISSUE TITLE
Link to the Doc is dead 

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mumbleserver_ynh#17]
Hi, 
on https://yunohost.org/#  , the Doc link is dead ;)

**Comment by Jibec** [comment]
I don't understand, what is the issue? Do you mean, the one in https://yunohost.org/#/apps ?

**Comment by Jibec** [comment]
thanks for your issue @isAAAc , please re-open with more details

**Comment by isAAAc** [comment]
Sorry, i was very bussy those days
> I don't understand, what is the issue? Do you mean, the one in https://yunohost.org/#/apps ?

Yes, you select the "All Apps" in filters, and type mumble, 
then you can see "Mumble Server" and "Mumble Admin Plugin"
with a "doc" link in central bottom, -> those links are not really dead , but the pages dont exist : 
https://yunohost.org/#/app_mumbleserver_fr
https://yunohost.org/#/app_mumble_admin_plugin_fr
