### ISSUE TITLE
yunohost app install: /dev/tty: No such device or address

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/mumbleserver_ynh#2]
Upon installation from command line I get

`Restarting mumble-server (via systemctl): mumble-server.serviceFailed to open /dev/tty: No such device or address`

Is this something to worry about?

**Comment by matlink** [comment]
Not really, it's not linked to mumble server installation.

Le 09/05/2016 08:30, fgro a écrit :

> Upon installation from command line I get
> 
> |Restarting mumble-server (via systemctl): mumble-server.serviceFailed
> to open /dev/tty: No such device or address|
> 
> Is this something to worry about?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/matlink/mumbleserver_ynh/issues/2

## 

Matlink - Sysadmin matlink.fr
Sortez couverts, chiffrez vos mails : https://café-vie-privée.fr/
XMPP/Jabber : matlink@matlink.fr
Clé publique PGP : 0x186BB3CA
Empreinte Off-the-record : 572174BF 6983EA74 91417CA7 705ED899 DE9D05B2

**Comment by M5oul** [comment]
That's not a mumble package issue.
It can be closed.
