### ISSUE TITLE
Missing restart or reload after certificate renewal

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/mumbleserver_ynh#23]
When a LE certificate renewal occurred, the mumblerserver service should be restarted/reloaded.

I don't know if the core provides the necessary hook to do that

**Comment by Jibec** [comment]
Indeed it doesn't exist: https://yunohost.org/#/packaging_apps_hooks_fr

I'll try to ping aleks
-- 
Jean-Baptiste Holcroft

**Comment by alexAubin** [comment]
Uh yeah we should implement some hooks like it's already available for user creation and similar stuff :s

**Comment by alexAubin** [comment]
c.f. https://github.com/YunoHost/yunohost/pull/586 (I yolocommited so this needs some testing /o\)

**Comment by julienmalik** [comment]
It seems mumble needs a full restart to read the new certificates. A reload is not sufficient

**Comment by Jibec** [comment]
should be fixed by https://github.com/YunoHost-Apps/mumbleserver_ynh/pull/27
It requires YunoHost 3.4, actually in testing.
I didn't test it. I'll really test once 3.4 is released officially.

@alexAubin I used a hack to find the app id, I hope it's the correct way to do it ;)

**Comment by alexAubin** [comment]
(a hack to find the app id ? not sure what you mean o.O)

**Comment by Jibec** [comment]
I used the hook file name to guess what's the value of $app

**Comment by Jibec** [comment]
I don't know why I never closed this issue, the fix was done long ago: https://github.com/YunoHost-Apps/mumbleserver_ynh/commit/60ef2515b18c053f6b02af8bd5545e0c2700d8ae

please reopen if required
