### ISSUE TITLE
Can't connect to my server

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/mumbleserver_ynh#26]
Hello,

I entered the information mentioned in the mail that my mumble instance sent me, but the button «connect» stays greyed, and i don't understand why.

**Comment by Jibec** [comment]
which client do you use? I test this app with Mumble 1.2.19, please try with this one if it isn't the case.

**Comment by farvardin** [comment]
I have installed this package as well on 2 different servers (it's version 1.2.8 from 2014). I've tried to connect to it with the linux Mumble client version 1.2.19, but I see no ping and the connect button is greyed out too. 

I've also tried the Plumble android client, with no success.

The 64738 port seems to be open in the iptables of yunohost:
-A INPUT -p tcp -m tcp --dport 64738 -j ACCEPT
-A INPUT -p udp -m udp --dport 64738 -j ACCEPT

I don't know how to investigate further.

**Comment by farvardin** [comment]
I understand the problem, I've written in the Mumble client the full URL, including https:// (on the YunoHost installation, it was also written: "URL     https://website.info". If I use the IP address, or only "website.info", then the connect button is no longer grey!
