### ISSUE TITLE
yunohost integration

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/mumbleserver_ynh#3]
from other ynh apps I'm used to get a "box" in "/yunohost" ... then usually some namespace e.g. "/mumbleserver" where one could adjust settings. Not the case for this app, is this intentional or just outdated? 

Thank you kindly

**Comment by ghost** [comment]
oh I just found this https://github.com/matlink/mumble_admin_plugin_ynh

**Comment by matlink** [comment]
Mumble server is not a webapp, only a daemon running on your server
(that is why there is no tile). You should now install the mumble client
and connect to your server.

Le 09/05/2016 08:34, fgro a écrit :

> from other ynh apps I'm used to get a "box" in "/yunohost" ... then
> usually some namespace e.g. "/mumbleserver" where one could adjust
> settings. Not the case for this app, is this intentional or just
> outdated?
> 
> Thank you kindly
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/matlink/mumbleserver_ynh/issues/3

## 

Matlink - Sysadmin matlink.fr
Sortez couverts, chiffrez vos mails : https://café-vie-privée.fr/
XMPP/Jabber : matlink@matlink.fr
Clé publique PGP : 0x186BB3CA
Empreinte Off-the-record : 572174BF 6983EA74 91417CA7 705ED899 DE9D05B2
