### ISSUE TITLE
updating murmur (mumble server)

### ISSUE THREAD

**Issue by farvardin** [YunoHost-Apps/mumbleserver_ynh#36]
Hello,

with the release of Ubuntu 20.04, the mumble client is no longer compatible with the server (murmur) skipped with Debian and the mumbleserver_ynh. 

This server version is 1.2.18, which was released in december 2016!

The update is really straightforward, here is what I did:

> wget https://github.com/mumble-voip/mumble/releases/download/1.3.0/murmur-static_x86-1.3.0.tar.bz2
> tar xfvj murmur-static_x86-1.3.0.tar.bz2
> sudo service mumbleserver stop
> sudo cp murmur-static_x86-1.3.0/murmur.x86 /usr/sbin/murmurd
> sudo service mumbleserver start

maybe you could officially update the server to latest version?

**Comment by hirgelbirgel** [comment]
Hi!
this procedure is not working on a raspberry pi. Do you have an idea how to make it work on an arm based board? Or did i miss something? After restarting the mumbleserver the service entered a failed state (code=exited, status=203/EXEC) Do i have to compile the static version myself in order to resolve my issue?

**Comment by hirgelbirgel** [comment]
Nevermind, i compiled it myself and it worked like a charm! :) you just have to follow the description [here](https://wiki.mumble.info/wiki/BuildingLinux#Getting_the_source) and copy the resulting murmurd file...

**Comment by farvardin** [comment]
yes, raspberry pi is using an ARM CPU!

**Comment by makotoworkshop** [comment]
Yes farvardin !!
My problems are sovled with your helpy message ^^

I've take the V 1.3.2, https://github.com/mumble-voip/mumble/releases/download/1.3.2/murmur-static_x86-1.3.2.tar.bz2
It's ok ^^

Thanks you !
