### ISSUE TITLE
yunohost app remove: uses invalid yunohost command 'services'

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/mumbleserver_ynh#4]
```
sudo yunohost services remove mumble-server
usage: yunohost [-h] [-v]
                {domain,monitor,service,firewall,tools,app,hook,dyndns,backup,user}
                ...
yunohost: error: invalid choice: 'services' (choose from 'domain', 'monitor', 'service', 'firewall', 'tools', 'app', 'hook', 'dyndns', 'backup', 'user')
```

**Comment by matlink** [comment]
No time to fix it, please submit a PR if you want :)

Le 09/05/2016 09:09, fgro a écrit :

> |sudo yunohost services remove mumble-server usage: yunohost [-h] [-v]
> {domain,monitor,service,firewall,tools,app,hook,dyndns,backup,user}
> ... yunohost: error: invalid choice: 'services' (choose from 'domain',
> 'monitor', 'service', 'firewall', 'tools', 'app', 'hook', 'dyndns',
> 'backup', 'user') |
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/matlink/mumbleserver_ynh/issues/4

## 

Matlink - Sysadmin matlink.fr
Sortez couverts, chiffrez vos mails : https://café-vie-privée.fr/
XMPP/Jabber : matlink@matlink.fr
Clé publique PGP : 0x186BB3CA
Empreinte Off-the-record : 572174BF 6983EA74 91417CA7 705ED899 DE9D05B2
