### ISSUE TITLE
Change passwords

### ISSUE THREAD

**Issue by PxBCPG** [YunoHost-Apps/mumbleserver_ynh#46]
Everything in the title!
How to change password of the server/superuser ?

**Comment by dosch** [comment]
Yes, same issue here.
A few lines documentation on the 2 steps to take just after installation would be nice

**Comment by mrflos** [comment]
What i did:  
`sudo vi /var/www/mumbleserver/mumble-server.ini`

remove (or change) the password for `serverpassword=`, save and:  
`sudo service mumbleserver restart`

**Comment by lost-geographer** [comment]
The procedure for changing the SuperUser password (not the server password) has not been documented. The command is : `/usr/sbin/murmurd -ini /var/www/mumbleserver/mumble-server.ini -supw YourStrongPassword` (it's not the same as the one described in the [official documentation](https://wiki.mumble.info/wiki/Running_Murmur#Setting_the_SuperUser_Password)).

Tested on 1.3.4~ynh1. Do not forget to restart the *mumbleserver* service after running this command.
