### ISSUE TITLE
Add WebInterface

### ISSUE THREAD

**Issue by inrepublica** [YunoHost-Apps/mumbleserver_ynh#5]
It would be a good idea to install an webinterface for Mumble. [MumPI](https://github.com/Kissaki/MumPI) for example.

**Comment by M5oul** [comment]
There is already a [package to administrated Mumble](https://github.com/matlink/mumble_admin_plugin_ynh).
But, I couldn't make it works.

**Comment by inrepublica** [comment]
Ok, thanks!
