### ISSUE TITLE
Add Mumble-web!

### ISSUE THREAD

**Issue by nicopace** [YunoHost-Apps/mumbleserver_ynh#7]
Works like a charm, and allows people to use without a client.
https://github.com/Johni0702/mumble-web

**Comment by hferee** [comment]
I guess this would make sens as a separate app.

**Comment by nicopace** [comment]
It's really small to add it as a separate app... but of course.
Thanks!

**Comment by lenod** [comment]
I think small is good. You want apps to be as easy to maintain as possible.

**Comment by Jibec** [comment]
as Yunohost is about to be an enabler for people with low technical knoledge, I feel like I'll icnlude this here with an option.

**Comment by unklebonehead** [comment]
Can this be installed using MyCustomWebapp or does it need to be in the same directory as the mumble server?

**Comment by Jaxom99** [comment]
Turns out it uses Websockets, so the server also has to use them... So you should also setup https://github.com/novnc/websockify at the same time.
Clearly, using a different app would be better.

**Comment by jrd10** [comment]
HI,
YNH user as non-sysadmin :) and Interested in Mumble-Web

@Jaxom99 
Can you detail installation through YNH :)

Thank you

**Comment by Jaxom99** [comment]
> Can you detail installation through YNH :)

see this issue from the original project : https://github.com/Johni0702/mumble-web/issues/51

**Comment by jrd10** [comment]
HI,
thank you for this quick feedback.
I have seen it but I do not want to install an application on the server where YNH has been installed :).
So. No way to install it thank to YNH

Even with  MyCustomWebapp for instance as mentioned by @unklebonehead ?

Thank you for your time and consideration :)

**Comment by Jaxom99** [comment]
The app is not yet packaged, so no way to install it via YNH. 
But you should ask for it in the forum, maybe someone has some spare time at the moment 😉

**Comment by jrd10** [comment]
Hi @Jaxom99 
Thank you for your fast feedback.

The message is here...
https://forum.yunohost.org/t/about-this-fantastic-app-mumble-web-ynh-package/10609?u=jrelland

Feel free to add more information :+1: 

From José the Messenger :)

**Comment by Jibec** [comment]
Ok, I am starting to working on it. Could be really useful nowadays... I'll create a dedicated branch and invite you to test it and confirm it works.

**Comment by nicopace** [comment]
> Ok, I am starting to working on it. Could be really useful nowadays... I'll create a dedicated branch and invite you to test it and confirm it works.

Will be paying attention to it, can test in different scenarios if needed :)

**Comment by jrd10** [comment]
Bonjour,
en test chez Framasolft :)
https://forum.chatons.org/t/ameliorer-votre-instance-mumble-avec-mumble-web/937

Bravo et merci, José

**Comment by adipasquale** [comment]
I'd be up to help too @Jibec 🤚

**Comment by Jibec** [comment]
I did a test, it looks really easy to package, it installs and all 
but... I don't really understand how to properly the YunoHost nodejs 
helpers.
It does install, but I have no idea where and nginx requires to know 
where is the package.
I'll try figure it out tonight again, don't worry. I should have pushed 
my branch so all can have a look. I'll do that tonight, whatever 
happens!

**Comment by Jibec** [comment]
So, here is my current work, I did not had time to pursue the work tonight: https://github.com/YunoHost-Apps/mumbleserver_ynh/pull/32

It looks like I broke my package_check and have to redo it... (it is slow with my current computer)

My issue is as follow:
I'm installing the node package: https://github.com/YunoHost-Apps/mumbleserver_ynh/blob/web/scripts/install#L85
I should tell nginx where the node module is installed: https://github.com/YunoHost-Apps/mumbleserver_ynh/blob/web/conf/mumble-web.service#L12

**Comment by adipasquale** [comment]
hi @Jibec i haven't forgotten this I'll try and have a look this week

**Comment by nicopace** [comment]
@Jibec I can't find a way to test a branch... can you give us a set of steps to try it out?

**Comment by Gredin67** [comment]
@Jibec I installed your branch on a VM. mumble is working, but not access to web.mumble yet.

**Comment by alien2003** [comment]
I hope this will be possible. Mumble-web can be integrated with Element, btw

**Comment by ericgaspar** [comment]
**Mumble web** is now available as a separate app:

https://github.com/YunoHost-Apps/mumble-web_ynh
